# Generated by Django 4.1.1 on 2022-09-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.URLField(default='https://dummyimage.com/600x400/e0e0e0/878787.png&text=img', max_length=250),
        ),
    ]
